import { Resvg } from "@resvg/resvg-js";

export type Puzzle = {
  title?: string;
  bestMove?: string;
  description?: string;
};

export type RenderMeta = {
  username?: string;
  tagline?: string;
};

function escapeHtml(text: string): string {
  return (text || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

export async function generateDesign(
  puzzles: Puzzle[],
  meta: RenderMeta = {}
) {
  const width = 1200;
  const height = 1600;

  const username = meta.username ? `@${meta.username}` : "@chess-tee";
  const tagline = meta.tagline || "Your best chess moments";

  const topPuzzles = puzzles.slice(0, 5);

  let y = 160;
  const lines: string[] = [];

  lines.push(
    `<text x="80" y="100" font-size="56" font-family="Arial" font-weight="700" fill="#111">
      ${escapeHtml(username)}
    </text>`
  );

  lines.push(
    `<text x="80" y="140" font-size="26" font-family="Arial" fill="#444">
      ${escapeHtml(tagline)}
    </text>`
  );

  lines.push(
    `<line x1="80" y1="180" x2="${width - 80}" y2="180" stroke="#ddd" stroke-width="2" />`
  );

  for (let i = 0; i < topPuzzles.length; i++) {
    const p = topPuzzles[i];

    lines.push(
      `<text x="80" y="${y}" font-size="30" font-family="Arial" font-weight="700" fill="#111">
        ${escapeHtml(p.title || `Puzzle ${i + 1}`)}
      </text>`
    );
    y += 40;

    if (p.bestMove) {
      lines.push(
        `<text x="80" y="${y}" font-size="24" font-family="Arial" fill="#222">
          Best move: ${escapeHtml(p.bestMove)}
        </text>`
      );
      y += 34;
    }

    if (p.description) {
      lines.push(
        `<text x="80" y="${y}" font-size="22" font-family="Arial" fill="#555">
          ${escapeHtml(p.description)}
        </text>`
      );
      y += 32;
    }

    y += 30;

    lines.push(
      `<line x1="80" y1="${y}" x2="${width - 80}" y2="${y}" stroke="#eee" stroke-width="1" />`
    );
    y += 50;
  }

  lines.push(
    `<text x="80" y="${height - 80}" font-size="20" font-family="Arial" fill="#777">
      Generated by chess-tee-generator
    </text>`
  );

  const svg = `
<svg
  width="${width}"
  height="${height}"
  viewBox="0 0 ${width} ${height}"
  xmlns="http://www.w3.org/2000/svg"
>
  <rect x="0" y="0" width="${width}" height="${height}" fill="#ffffff" />
  ${lines.join("\n")}
</svg>
`;

  const resvg = new Resvg(svg, {
    fitTo: {
      mode: "width",
      value: width
    }
  });

  const pngBuffer = resvg.render().asPng();
  const pngBase64 = Buffer.from(pngBuffer).toString("base64");

  return {
    svg,
    png: `data:image/png;base64,${pngBase64}`
  };
}
