// backend/src/services/render.ts

import { Resvg } from "@resvg/resvg-js";

export type Puzzle = {
  title?: string;
  fen?: string;
  bestMove?: string;
  description?: string;
};

export type RenderMeta = {
  username?: string;
  tagline?: string;
};

function esc(s: string) {
  return (s || "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function wrapText(text: string, max = 54) {
  const words = (text || "").split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let cur = "";
  for (const w of words) {
    const next = cur ? `${cur} ${w}` : w;
    if (next.length > max) {
      if (cur) lines.push(cur);
      cur = w;
    } else {
      cur = next;
    }
  }
  if (cur) lines.push(cur);
  return lines;
}

export async function generateDesign(puzzles: Puzzle[], meta: RenderMeta = {}) {
  const W = 1200;
  const H = 1600;

  const username = meta.username ? `@${meta.username}` : "chess-tee";
  const tagline = meta.tagline || "Best moments, printed.";

  const top = (puzzles || []).slice(0, 5);

  // Simple SVG “poster” (black/white) – stable, compile-safe
  const lines: string[] = [];

  lines.push(
    `<text x="80" y="140" font-size="54" font-family="Arial, Helvetica, sans-serif" font-weight="700" fill="#111">${esc(
      username
    )}</text>`
  );
  lines.push(
    `<text x="80" y="200" font-size="26" font-family="Arial, Helvetica, sans-serif" fill="#444">${esc(
      tagline
    )}</text>`
  );

  // Divider
  lines.push(`<line x1="80" y1="240" x2="${W - 80}" y2="240" stroke="#ddd" stroke-width="2" />`);

  // Puzzles list
  let y = 320;
  top.forEach((p, i) => {
    const title = p.title || `Puzzle #${i + 1}`;
    const move = p.bestMove ? `Best move: ${p.bestMove}` : "";
    const desc = p.description || "";

    lines.push(
      `<text x="80" y="${y}" font-size="30" font-family="Arial, Helvetica, sans-serif" font-weight="700" fill="#111">${esc(
        title
      )}</text>`
    );
    y += 44;

    if (move) {
      lines.push(
        `<text x="80" y="${y}" font-size="24" font-family="Arial, Helvetica, sans-serif" fill="#222">${esc(
          move
        )}</text>`
      );
      y += 38;
    }

    if (desc) {
      const wrapped = wrapText(desc, 64).slice(0, 3);
      for (const l of wrapped) {
        lines.push(
          `<text x="80" y="${y}" font-size="22" font-family="Arial, Helvetica, sans-serif" fill="#555">${esc(
            l
          )}</text>`
        );
        y += 32;
      }
      y += 12;
    }

    // small separator
    lines.push(`<line x1="80" y1="${y}" x2="${W - 80}" y2="${y}" stroke="#eee" stroke-width="2" />`);
    y += 54;
  });

  // Footer
  lines.push(
    `<text x="80" y="${H - 90}" font-size="22" font-family="Arial, Helvetica, sans-serif" fill="#777">${esc(
      "Generated by chess-tee-generator"
    )}</text>`
  );

  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg">
  <rect x="0" y="0" width="${W}" height="${H}" fill="#ffffff"/>
  ${lines.join("\n  ")}
</svg>`;

  // Render PNG from SVG
  const resvg = new Resvg(svg, {
    fitTo: { mode: "width", value: W },
  });

  const pngData = resvg.render().asPng();
  const pngBase64 = Buffer.from(pngData).toString("base64");

  return {
    svg,
    png: `data:image/png;base64,${pngBase64}`,
  };
}

